### ISSUE TITLE
Machine buys more BTC than the amount it can dispense

### ISSUE THREAD

**Issue by keo** [lamassu/lamassu-machine#47]
We had an edge case here (which probably isn't an edge case at all).

This is what happened:

Our transaction limit is 100,000 HUF (and requires 1 confirmation). There's 270,000 HUF in the dispenser.
- customer sells 100,000 HUF worth of Bitcoins
- he gets a redeem code and sends 1.65 to the QR code provided by the machine.
- customer sells 100,000 HUF again
- he gets a redeem code again and sends 1.65 the the next QR code provided
- customer does this a third time. He sells 100,000 HUF worth of Bitcoins.
- he gets a redeem code and sends 1.65 BTC to the 3rd QR code.

Transactions confirm, he gets an SMS, and wants to redeem. He is able to redeem the first two transactions, and for the 3rd one he sees an "Ooops... Sorry" screen.

Obviously what happened is that when calculating the available dispensable cash amount the system didn't take into account non-redeemed / non-confirmed incoing bitcoins (and their fit counterpart).

I got here, filled up the dispenser, and asked the guy to try redeeming again. He entered his phone number and the ATM said there's no pending transaction on that phone number, so I had to send his Bitcoins back.

**Comment by naconner** [comment]
This has been due to a discrepancy between the machine-side bills count and the server-side, which can be caused by the machine not updating the server count following a previous, successful dispense, due to a drop in connectivity and the machine not retrying.

v3 introduces indempotency and transaction staging, which should solve this. Currently in testing on Douros, and we'll have a version for Trofas soon. (https://support.lamassu.is/hc/en-us/categories/115000160112-Next-Gen-Beta-)
