### ISSUE TITLE
Transaction log is not in order. - Curious

### ISSUE THREAD

**Issue by Transisto** [lamassu/lamassu-machine#73]
![image](https://cloud.githubusercontent.com/assets/388716/14638031/413fcaf0-0603-11e6-9256-c183d7605a5b.png)

I sort them by date so I don't mind much but I'm very curious to know why transaction are not logged in order.

**Comment by naconner** [comment]
Hi @Transisto. I'm not aware of a reason why they should be logged other than in chronilogical order, or why they would. Which server version is this? (Find by running `npm -g ls lamassu-server`).

**Comment by Transisto** [comment]
This is lamassu-server@2.2.12

Doesn't get more random than that. 

![image](https://cloud.githubusercontent.com/assets/388716/15035643/2ed2a2c4-1252-11e6-978a-ee473e9f800f.png)

**Comment by Transisto** [comment]
Anyone else having their log file recorded randomly ? I don't have any problem sorting them by timestamp but I find this very odd and I'm scared of what else could happen if server was to go down at a bad time.

**Comment by naconner** [comment]
Thanks for the details. The date and the id column reflect when the record was generated. The way in which they're ordered by default in the database won't affect when or how the transaction is sent.

In fact, from the [PostgreSQL documentation](http://www.postgresql.org/docs/8.1/static/queries-order.html):

>  If sorting is not chosen, the rows will be returned in an unspecified order. The actual order in that case will depend on the scan and join plan types and the order on disk, but it must not be relied on. A particular output ordering can only be guaranteed if the sort step is explicitly chosen.

Since a `SORT` is not performed during the export of the logs, the resulting order is arbitrary.

**Comment by Transisto** [comment]
Thanks - Closed
